### ISSUE TITLE
Корректировки плана

### ISSUE THREAD

**Issue by ArRomanov** [falkona/qa-diploma#3]
1. **Сценарии**
* В сценариях, где проверяется прошедшие месяц/год, вероятно, проверка должна проходить не на фронтенде, а на бекенде, потому что, обычно, логические вычисления/проверки проводят именно на сервисе, чтобы не влиять на производительность вашего компьютера, а на фронтенде проводят лишь первичную валидацию.
* В 11 сценарии опечатались: вы проверяете кейс без номера карты, а ожидаете ошибку по владельцу.
* Можно еще добавить кейс с отправкой номера карты, которого нет в списке тестовых данных. Интересно, как в таком случае поведет себя сервис.
2. **Инструменты**
* Можно объединить `Библиотеки` и `Отчетность` в `Инструменты` и добавить туда еще язык программирования, хранилище кода.
* По заданию необходимо написать обоснование выбора инструмента. По сути, выбора у нас нет, но если бы и был, то выбирать пришлось бы - напишите сильные, на ваш взгляд, стороны выбранных инструментов.
3. **Риски**
* Что вы имели в виду под низкой продуктивностью? Вашу продуктивность? Если да, то так не пойдет. Заказчика не очень будет интересовать, в какой стадии у вас луна или какова мощность магнитных бурь. Либо вы имели в виду не вашу продуктивность, а в более общем смысле? Тогда это слишком обобщенно, нужно расписать риски более детально, от чего может зависеть общая продуктивность.
* Что еще можно учесть. Вам предстоит проверить работу приложения с двумя базами данных (mysql/postgres). Вы подумали над стратегией, как это организовать? Вероятно, могут возникнуть проблемы с настройкой такой инфраструктуры - это риск.
* У вас нет документации с требованиями к сервису, к тому что должно пройти форму, а что не должно, где и какие проверки должны происходить. Если работа приложения не совпадет с ожидаемым вами, то вы можете потерять время на корректировку кейсов. Риск? Риск.
4. **Оценка**
* Оценку чаще всего пишут в _человекочасах_ или _человекоднях_ - сколько нужно времени (часов или дней по 8ч.) одному человеку для выполнения работы. Так становится более понятно, какая нужна команда для выполнения в нужный срок (при возможности одновременной работы нескольких человек).
* В общем, оценили хорошо, но есть один момент. Риски, как правило, не превышают 25% от вашей оценки, поэтому к оценке "без рисков" можно добавить часы, чтобы риски не превышали 15-25%.
* Еще можно отдельно прикинуть время на написание отчетности. Вам же не просто отчет allure сгенерить, вам еще нужно написать итоговый отчет с входными и выходными показателями.

**Comment by falkona** [comment]
**Сценарии:**
1. Валидация даты происходит на форме, если месяц / год неправильный, то на бэк ничего не уходит. Пока что оставила только проверки на форме.
2. 11 сценарий исправила
3. Добавила кейс 13 - проверка карты, которой нет в списке

**Comment by falkona** [comment]
Инструменты
1. Дописала ЯП, хранилище кода
2 Дописала преимущества выбранных инструментов

**Comment by falkona** [comment]
Скорректировала риски

**Comment by falkona** [comment]
Скорректировала оценку
