### ISSUE TITLE
Как проверить записи в БД

### ISSUE THREAD

**Issue by falkona** [falkona/qa-diploma#4]
Отредактировала позитивные кейсы, добавила в них проверку, что при транзакции создается запись в БД. Вопрос: как определить, что в результате теста действительно была добавлена конкретная запись в БД? Там есть 2 идентификатора, которые непонятно как генерятся. Соответственно, непонятно, как искать нужную запись в БД.

**Comment by coursar** [comment]
Наверное, стоит искать не по идентификаторам, а по данным.

**Comment by falkona** [comment]
@coursar 
После запуска SUT у меня 3 таблицы в БД
```
mysql> show tables;
+-----------------------+
| Tables_in_app         |
+-----------------------+
| credit_request_entity |
| order_entity          |
| payment_entity        |
+-----------------------+
```
и из данных там только время и статус. Не очень показательно, как мне кажется

**Comment by coursar** [comment]
Т.е. сумма нигде не хранится и названия табличек вам ни о чём не говорят? Исследовательское тестирование подразумевает необходимость подготовки выводов на основании сделанного анализа.

Вы можете задавать уточняющие вопросы, но это должны быть вопросы, сформулированные на базе проведённого вам анализа.

Для начала неплохо бы выяснить, в какие таблицы и какие данные записываются, если вы просто покупаете, и чем они отличаются от покупки в кредит.

**Comment by falkona** [comment]
@coursar 
Я прошла сценарий "Покупка прошла успешно" и после этого в БД появились записи 
```
mysql> select * from order_entity;
+--------------------------------------+----------------------------+-----------+--------------------------------------+
| id                                   | created                    | credit_id | payment_id                           |
+--------------------------------------+----------------------------+-----------+--------------------------------------+
| 534c6c09-6879-442a-a124-fc118822943a | 2019-12-06 11:03:25.226000 | NULL      | f68a7c68-8b4e-4230-a775-dcea4bdf3b8d |
+--------------------------------------+----------------------------+-----------+--------------------------------------+
1 row in set (0.00 sec)

mysql> select * from payment_entity;
+--------------------------------------+---------+----------------------------+----------+--------------------------------------+
| id                                   | amount  | created                    | status   | transaction_id                       |
+--------------------------------------+---------+----------------------------+----------+--------------------------------------+
| 2ecba0ef-570b-4046-94d3-8e420146eeca | 4500000 | 2019-12-06 11:03:25.121000 | APPROVED | f68a7c68-8b4e-4230-a775-dcea4bdf3b8d |
+--------------------------------------+---------+----------------------------+----------+--------------------------------------+
```
А если, например, я запущу автотесты и параллельно пройду этот же сценарий руками, и две транзакции пройдут одновременно? Как понять, какая из них была создана автотестом? 
Конечно, можно исходить из того, что тесты запускаются только последовательно, и в параллели с ними никто ничего не делает, и проверять состояние БД до и после теста, чтобы найти ту самую запись... Выглядит костыльно

**Comment by coursar** [comment]
Какой смысл параллельно делать то же самое руками? Вы запускаете SUT с чистым состоянием, выполняете тест, после чего возвращаете SUT в прежнее состояние.

В какой из лекций было, что обязательно параллельно с тем, как у вас идёт авто-тест вы должны обязательно тестировать то же самое руками? Говорилось лишь про то, что **прежде чем писать авто-тест**, нужно пройтись руками и посмотреть всё.

**Comment by falkona** [comment]
ок, понятно
