### ISSUE TITLE
Как фронт должен реагировать, если с бэка приходит код ответа 400?

### ISSUE THREAD

**Issue by falkona** [falkona/qa-diploma#5]
Шаги: 
Заполнить поля формы "Путешествие дня" значениями:
- номер карты: 1234000000000000
- месяц: 08
- год: 22
- владелец: Нос Дарья
- cvc: 789

ОР: система оповещает пользователя, что номер карты не найден (?)
ФР: одновременно появляются нотификации "Успешно" и "Ошибка"

**Comment by ArRomanov** [comment]
В задании написано, что сервис оплат не настоящий, а просто является заглушкой. Ну и документации у нас никакой нет. Поэтому, если у нас сервис не падает на этих данных, а просто отвечает ошибкой, то, думаю, можно и проверить наличие этой ошибки. Вот по поводу нотификации **Успешно** хороший вопрос. Попробуйте локализовать, в каких случаях появляется такое сообщение. Ведь, ответ от сервера приходит один и, соответственно, сообщение должно быть одно - **Успешно** или **Ошибка**.

**Comment by falkona** [comment]
Тогда для проверки этой ошибки сделаю отдельный тест на REST
