### ISSUE TITLE
В таблицу payment_entity записывается некорректная сумма

### ISSUE THREAD

**Issue by falkona** [falkona/qa-diploma#6]
Шаги:
Заполнить форму "Путешествие дня" значениями:
- Номер карты: 4444444444444441
- Месяц: 08
- Год: 23
- Владелец: Дарья
- сvc: 456
Нажать Продолжить
Выполнить запрос к БД
```
select * from payment_entity;
```

ОР: в поле amount значение соответствует тому, что указано на форме - 45 000 рублей
ФР: в поле amount значение - 4 500 000 
```
mysql> select * from payment_entity;
+--------------------------------------+---------+----------------------------+----------+--------------------------------------+
| id                                   | amount  | created                    | status   | transaction_id                       |
+--------------------------------------+---------+----------------------------+----------+--------------------------------------+
| f184915a-2482-48d9-84b4-2469d9538e8b | 4500000 | 2019-12-09 09:59:00.227000 | APPROVED | 8876c99b-665f-4890-a7bc-7f5bc0fc61d1 |
+--------------------------------------+---------+----------------------------+----------+--------------------------------------+
```

**Comment by ArRomanov** [comment]
Сегодня обсуждал этот момент с Ильназом. Дело в том, что денежные суммы часто принято хранить в значении "копейки", чтобы при различных расчетах и округлениях ничего не потерять. Все конвертации, соответственно, производятся в приложении.

Вот статья на эту тему https://habr.com/ru/post/309812/

**Comment by falkona** [comment]
Значит, не баг
